### ISSUE TITLE
[FR] better work with focus plugin

### ISSUE THREAD

**Issue by danieltomasz** [NomarCub/obsidian-hide-sidebars-on-window-resize#1]
Great plugin! 
Only issue I have that the  Hide Bar plugin extend sidebars while in focused mode when using this plugin (plugin hide everything that is not a current panel)
https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/38#issuecomment-1296828577
Are there a quick hack that the author of Focus plugin might implement to avoid extending sidebars when resizing  while being in the focused mode?

**Comment by NomarCub** [comment]
Hi!
The other plugin has a `focusModeActive` variable that I think I can access too. Should collapsing and expanding sidebars by this plugin not happen at all when focus mode is active?

**Comment by NomarCub** [comment]
@danieltomasz please respond if you still want this. I'll close this issue in 2 weeks otherwise.

**Comment by NomarCub** [comment]
Comment here if you want this reopened.
